baseurl = "https://pbar.me/"
languageCode = "en-us"
title = "Pierce Bartine"
theme = "hello-friend"
copyright = "2018 Pierce Bartine"
paginate = 5

[params]
  subtitle = "A simple theme for Hugo"

[params.logo]
  logoText = "cat pbar.txt"
#   or
#
#   path = "/img/your-example-logo.svg"
#   alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
