baseurl = "https://bartine.dev/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  defaultTheme = "dark"
  showReadingTime = true

[params.logo]


[languages]
  [languages.en]
    title = "Pierce Bartine"
    subtitle = "Blog"
    keywords = "software"
    copyright = "All is waves — Schrödinger"
    menuMore = "Show more"
    writtenBy = "By"
    readMore = "Read"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      path = "/images/logo.png"
      alt = "Bartine"
      logoHomeLink = "/"
