baseurl = "https://pbar.me/"
languageCode = "en-us"
title = "pbar"
theme = "hello-friend"
copyright = "© 2019 Pierce Bartine"
paginate = 5

[params]
  subtitle = "Pierce's blog"
  # "light" or "dark"
  defaultTheme = "light"

[params.logo]
  logoText = "bat pbar.me"
  # path = "/images/logo.png"
  # alt = "Your example logo alt text"

# [menu]
#   [[menu.main]]
#     identifier = "about"
#     name = "About"
#     url = "/about"
