baseURL = "https://pbar.me"
title = "Pierce Bartine's blog"
theme = "hugo-notepadium"
copyright = "© 2021 Pierce Bartine"

languageCode = "en"  # for the RSS generation
defaultContentLanguage = "en"

hasCJKLanguage = true

enableRobotsTXT = true

# Enable relativeURLs if your site hosted on GitHub.io
#relativeURLs = true

# Enable Disqus
#disqusShortname = "XXX"

# Google Analytics
#googleAnalytics = "UA-123-45"

ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "Mon, Jan 2, 2006"  # if unset, default is "2006-01-02"
readingTime = true  # show reading time after article date
logo = "img/favicon.png"
# slogan = "All is waves — Schrödinger"
#license = "<a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/><img alt=Creative Commons License style=border-width:0 src=https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png /></a><br />This work is licensed under a <a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>."
ipv6ready = false

[params.assets]
# css = ["css/fonts.css"]

[params.comments]
enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.share]
enable = false  # En/Disable share globally, default: false. You can always enable share on per page.
addThisId = ""
inlineToolId = ""

[params.math]
enable = false # load math globally, default: false. You can always enable math on per page.
use = "katex"  # builtin: "katex", "mathjax".  default: "katex"

[params.syntax]
use = ""  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "github"
darkTheme = "github-dark"

[params.profile]
  enable = true
  avatar = "img/profpic.jpg"
  name = "Pierce Bartine"
  bio = "All is waves — Schrödinger"  # support markdown syntax
  twitter = "pbar_"  # https://twitter.com/XXX
  github = "pbar1"  # https://github.com/XXX
  docker = "pbar1"

[params.nav]
showCategories = false      # /categories/
showTags = true             # /tags/

[[params.nav.custom]]
title = "About"
url = "/about/"
